# Supervised training config
n_GPUs: 1
batch_size: 16
model: ResUNetGenerator

do_validate: True
validate_every: 10
do_test: True

n_feats: 64
num_feat: 32
n_scales: 1

use_sa: True
use_edge_attention: True
use_spixel_attention: True
use_unsam_attention: True

loss: 1.0*L1+0.4*LPIPS+0.5*FrequencyLoss+0.2*NeighborLoss+0.01*ADV
metric: PSNR,SSIM,LPIPS

use_spectral_norm: True
lr: 2e-4
lr_D: 1e-4
milestones: [500, 700, 900]
end_epoch: 1000
save_results: part
amp: True
save_every: 10
scheduler: warm_multistep

data_root: /kaggle/input/datasets/sagatha/gopro-paired   
clip_grad: 1.0
freq_disc_feats: 64
